<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Serendipity" failures="3" tests="11" name="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" time="13.054" errors="0" timestamp="07 Mar 2024 12:16:22 GMT" skipped="0">
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyBankManagerLoginBtnFunctionality" time="1.304"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyBankManagerLogin" time="1.411"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyInvalidFnameBankManagerLogin" time="0.989">
    <failure message="First name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: First name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidFnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyInvalidFnameBankManagerLogin -->
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyInvalidLnameBankManagerLogin" time="0.993">
    <failure message="Last name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Last name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidLnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyInvalidLnameBankManagerLogin -->
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyEmptyFieldBankManagerLogin" time="2.179"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyDuplicateBankManagerLogin" time="0.951">
    <failure message="Mandatory fields are not working. New issue. expected [Pop-up validation: Customer may be duplicate.] but found [Pop-up validation: Customer added successfully]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Mandatory fields are not working. New issue. expected [Pop-up validation: Customer may be duplicate.] but found [Pop-up validation: Customer added successfully]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyDuplicateBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyDuplicateBankManagerLogin -->
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyOpenAccountFunctionality" time="1.779"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByName" time="0.957"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByID" time="0.568"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByPostCode" time="0.580"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="deleteCustomerFunctionality" time="1.343"/>
</testsuite> <!-- com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest -->
