<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Serendipity" failures="7" tests="33" name="GWB-Tests-Chrome" time="68.631" errors="0" timestamp="12 Mar 2024 18:58:13 GMT">
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifyTitle" time="1.454"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifyHomeBtn" time="0.142"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifycustLoginBtn" time="0.093"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifybankManagerLoginBtn" time="0.067"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifyHomeBtnFunctionality" time="0.422"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifycustLoginBtnFunctionality" time="0.618"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifybankManagerLoginBtnFunctionality" time="1.012"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifyNonAccountCustomersFunctionality" time="4.429"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyBankManagerLoginBtnFunctionality" time="1.353"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyBankManagerLogin" time="1.495"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyInvalidFnameBankManagerLogin" time="1.091">
    <failure type="java.lang.AssertionError" message="First name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]">
      <![CDATA[java.lang.AssertionError: First name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidFnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:44)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyInvalidFnameBankManagerLogin -->
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyInvalidLnameBankManagerLogin" time="1.008">
    <failure type="java.lang.AssertionError" message="Last name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]">
      <![CDATA[java.lang.AssertionError: Last name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidLnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:49)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyInvalidLnameBankManagerLogin -->
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyEmptyFieldBankManagerLogin" time="2.286"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyDuplicateBankManagerLogin" time="2.482"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyOpenAccountFunctionality" time="2.671"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByName" time="2.248"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByID" time="0.692"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByPostCode" time="0.511"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="deleteCustomerFunctionality" time="1.233"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifycustLoginBtnFunctionality" time="5.795"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifyCustomerLogin" time="2.542"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="depositValidAmount" time="3.055"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="depositInValidAmount" time="0.861">
    <failure type="java.lang.AssertionError" message="No warning raised. New issue detected expected [Deposit Successful] but found [Invalid Input]">
      <![CDATA[java.lang.AssertionError: No warning raised. New issue detected expected [Deposit Successful] but found [Invalid Input]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.depositInValidAmount(CustomerLoginFunctionalitiesTest.java:55)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- depositInValidAmount -->
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="depositDecimalAmount" time="0.704"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="withdrawValidAmount" time="4.585"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="withdrawInValidAmount" time="1.639">
    <failure type="java.lang.AssertionError" message="No warning raised. New issue detected expected [Transaction successful] but found [Invalid Input]">
      <![CDATA[java.lang.AssertionError: No warning raised. New issue detected expected [Transaction successful] but found [Invalid Input]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.withdrawInValidAmount(CustomerLoginFunctionalitiesTest.java:76)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- withdrawInValidAmount -->
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="withdrawDecimalAmount" time="0.796"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="withdrawInsufficientAmount" time="0.738"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="transactionResetFunctionalities" time="2.475">
    <failure type="java.lang.AssertionError" message="No warning raised. Major Issue detected. Balance is resetting, too. expected [Data reset successful] but found [Data reset unsuccessful]">
      <![CDATA[java.lang.AssertionError: No warning raised. Major Issue detected. Balance is resetting, too. expected [Data reset successful] but found [Data reset unsuccessful]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.transactionResetFunctionalities(CustomerLoginFunctionalitiesTest.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- transactionResetFunctionalities -->
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="transactionBackFunctionalities" time="0.336"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifyLogoutFunctionality" time="0.404"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifyPostLogoutFunctionality" time="0.38">
    <failure type="java.lang.AssertionError" message="Customer is able to visit the session after logging out. New issue expected [Customer is not able to visit the session after logging out.] but found [Customer is able to visit the session after logging out. New issue]">
      <![CDATA[java.lang.AssertionError: Customer is able to visit the session after logging out. New issue expected [Customer is not able to visit the session after logging out.] but found [Customer is able to visit the session after logging out. New issue]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyPostLogoutFunctionality(CustomerLoginFunctionalitiesTest.java:115)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPostLogoutFunctionality -->
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifyredirectToNonaccessablePageFunctionality" time="0.349">
    <failure type="java.lang.AssertionError" message="Customer is able to access the account after logging out. New issue expected [Customer is not access the account after logging out.] but found [Customer is able to access the account after logging out. New issue]">
      <![CDATA[java.lang.AssertionError: Customer is able to access the account after logging out. New issue expected [Customer is not access the account after logging out.] but found [Customer is able to access the account after logging out. New issue]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyredirectToNonaccessablePageFunctionality(CustomerLoginFunctionalitiesTest.java:120)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyredirectToNonaccessablePageFunctionality -->
</testsuite> <!-- GWB-Tests-Chrome -->
