<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Serendipity" failures="8" tests="32" name="GWB-Tests" time="39.538" errors="0" timestamp="07 Mar 2024 12:16:22 GMT">
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifyTitle" time="0.694"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifyHomeBtn" time="0.132"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifycustLoginBtn" time="0.098"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifybankManagerLoginBtn" time="0.07"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifyHomeBtnFunctionality" time="0.285"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifycustLoginBtnFunctionality" time="0.569"/>
  <testcase classname="com.crm.qa.testcases.HomeDashBoardTest" name="VerifybankManagerLoginBtnFunctionality" time="0.572"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyBankManagerLoginBtnFunctionality" time="1.304"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyBankManagerLogin" time="1.411"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyInvalidFnameBankManagerLogin" time="0.989">
    <failure type="java.lang.AssertionError" message="First name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]">
      <![CDATA[java.lang.AssertionError: First name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidFnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:41)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyInvalidFnameBankManagerLogin -->
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyInvalidLnameBankManagerLogin" time="0.993">
    <failure type="java.lang.AssertionError" message="Last name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]">
      <![CDATA[java.lang.AssertionError: Last name is containing special characters and numbers. New issue expected [Pop-up validation: Unexpected or no success message] but found [Pop-up validation: Customer added successfully]
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyInvalidLnameBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:46)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyInvalidLnameBankManagerLogin -->
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyEmptyFieldBankManagerLogin" time="2.179"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyDuplicateBankManagerLogin" time="0.951">
    <failure type="java.lang.AssertionError" message="Mandatory fields are not working. New issue. expected [Pop-up validation: Customer may be duplicate.] but found [Pop-up validation: Customer added successfully]">
      <![CDATA[java.lang.AssertionError: Mandatory fields are not working. New issue. expected [Pop-up validation: Customer may be duplicate.] but found [Pop-up validation: Customer added successfully]
	at com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest.VerifyDuplicateBankManagerLogin(BankManagerLoginFunctionalitiesTest.java:57)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyDuplicateBankManagerLogin -->
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="VerifyOpenAccountFunctionality" time="1.779"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByName" time="0.957"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByID" time="0.568"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="searchCustomersFunctionalityByPostCode" time="0.58"/>
  <testcase classname="com.crm.qa.testcases.BankManagerLoginFunctionalitiesTest" name="deleteCustomerFunctionality" time="1.343"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifycustLoginBtnFunctionality" time="1.206"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifyCustomerLogin" time="0.99"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="depositValidAmount" time="1.662"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="depositInValidAmount" time="0.702">
    <failure type="java.lang.AssertionError" message="No warning raised. New issue detected expected [Deposit Successful] but found [Invalid Input]">
      <![CDATA[java.lang.AssertionError: No warning raised. New issue detected expected [Deposit Successful] but found [Invalid Input]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.depositInValidAmount(CustomerLoginFunctionalitiesTest.java:52)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- depositInValidAmount -->
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="depositDecimalAmount" time="0.685"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="withdrawValidAmount" time="1.472"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="withdrawInValidAmount" time="1.092">
    <failure type="java.lang.AssertionError" message="No warning raised. New issue detected expected [Transaction successful] but found [Invalid Input]">
      <![CDATA[java.lang.AssertionError: No warning raised. New issue detected expected [Transaction successful] but found [Invalid Input]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.withdrawInValidAmount(CustomerLoginFunctionalitiesTest.java:73)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- withdrawInValidAmount -->
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="withdrawDecimalAmount" time="0.668"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="withdrawInsufficientAmount" time="0.687"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="transactionResetFunctionalities" time="0.791">
    <failure type="java.lang.AssertionError" message="No warning raised. Major Issue detected. Balance is resetting, too. expected [Data reset successful] but found [Data reset unsuccessful]">
      <![CDATA[java.lang.AssertionError: No warning raised. Major Issue detected. Balance is resetting, too. expected [Data reset successful] but found [Data reset unsuccessful]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.transactionResetFunctionalities(CustomerLoginFunctionalitiesTest.java:92)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- transactionResetFunctionalities -->
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="transactionBackFunctionalities" time="0.23"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifyLogoutFunctionality" time="0.278"/>
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifyPostLogoutFunctionality" time="0.308">
    <failure type="java.lang.AssertionError" message="Customer is able to visit the session after logging out. New issue expected [Customer is not able to visit the session after logging out.] but found [Customer is able to visit the session after logging out. New issue]">
      <![CDATA[java.lang.AssertionError: Customer is able to visit the session after logging out. New issue expected [Customer is not able to visit the session after logging out.] but found [Customer is able to visit the session after logging out. New issue]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyPostLogoutFunctionality(CustomerLoginFunctionalitiesTest.java:110)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyPostLogoutFunctionality -->
  <testcase classname="com.crm.qa.testcases.CustomerLoginFunctionalitiesTest" name="VerifyredirectToNonaccessablePageFunctionality" time="0.277">
    <failure type="java.lang.AssertionError" message="Customer is able to access the account after logging out. New issue expected [Customer is not access the account after logging out.] but found [Customer is able to access the account after logging out. New issue]">
      <![CDATA[java.lang.AssertionError: Customer is able to access the account after logging out. New issue expected [Customer is not access the account after logging out.] but found [Customer is able to access the account after logging out. New issue]
	at com.crm.qa.testcases.CustomerLoginFunctionalitiesTest.VerifyredirectToNonaccessablePageFunctionality(CustomerLoginFunctionalitiesTest.java:115)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- VerifyredirectToNonaccessablePageFunctionality -->
</testsuite> <!-- GWB-Tests -->
